export const CardAllActivities = [
  {
    title: "Kecak Dance Uluwatu",
    price: "500.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: true,
    id: 0,
  },
  {
    title: "Kintamani Tour",
    price: "1.000.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: false,
    id: 1,
  },
  {
    title: "Rafting + Ubud Tour",
    price: "2.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: false,
    id: 2,
  },
  {
    title: "Balinese Food Culinary",
    price: "1.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: true,
    id: 3,
  },
  {
    title: "Kecak Dance Uluwatu",
    price: "500.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: true,
    id: 4,
  },
  {
    title: "Kintamani Tour",
    price: "1.000.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: true,
    id: 5,
  },
  {
    title: "Rafting + Ubud Tour",
    price: "2.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: true,
    id: 6,
  },
  {
    title: "Balinese Food Culinary",
    price: "1.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: true,
    id: 7,
  },
  {
    title: "Balinese Babi Guling",
    price: "1.000.000",
    image: "./images/hero_image1.png",
    desc: "testing",
    popular: false,
    id: 8,
  },
];

export const HeroImage = {
  Home: "./images/hero_image.jpg",
  PickupTransfer: "./images/airport-terminal.jpg",
  Activities: "./images/beach_club.jpg",
  Contact: "./images/NJ_BubbleGum_22.jpg",
};
